package com.ncist.stu.sever;

public interface MessageType {
    String MESSAGE_CREATE="MESSAGE_CREATE";//创建class
    String MESSAGE_ADD_STU="MESSAGE_COMM_MES";//普通信息包
    String MESSAGE_READ="MESSAGE_READ";//请求按条读取分区文件夹中的数据
    String MESSAGE_READ_BY_NAME="MESSAGE_READ_BY_NAME";
    String MESSAGE_READ_BY_ID="MESSAGE_READ_BY_ID";
    String MESSAGE_READ_CLASS="MESSAGE_READ_CLASS";
    String MESSAGE_CHANGE_STU="MESSAGE_CHANGE_STU";
    String MESSAGE_DELETE_STU="MESSAGE_DELETE_STU";


    String MESSAGE_READ_STU_TESTS="MESSAGE_READ_STU_TESTS";
    String MESSAGE_READ_TESTS="MESSAGE_READ_TESTS";
    String MESSAGE_READ_TEST_POINTS="MESSAGE_READ_TEST_POINTS";
    String MESSAGE_CREATE_TEST="MESSAGE_CREATE_TEST";
    String MESSAGE_DELETE_TEST="MESSAGE_DELETE_TEST";
}
